#+TITLE: JHJ Technology: Crossref

#+INCLUDE: "header.org"

* Crossref
:PROPERTIES:
:CUSTOM_ID: crossref
:END:

Crossref makes research outputs easy to find, cite, link, assess, and reuse.

Crossref metadata is open and available for reuse without restriction. There are currently 156,563,111 records,
these include information about research objects like articles, grants and awards, preprints, conference papers,
book chapters, datasets, and more. 

The information covers elements like titles, contributors, descriptions, dates, references, connecting identifiers
such as Crossref DOIs, ROR IDs and ORCID iDs, together with all sorts of metadata that helps to determine
provenance, trust, and reusability—such as funding, clinical trial, and license information.

In order to facilitate all of this Crossref has a number of large code bases and we have carried out a number
of challenging projects for them. 

They have a wide range of infrastructure and projects often involve pulling together lots of disparate data
sources and presenting a unified data format via their many APIs. 

We have carried out substantial work on their widely consumed public REST API. This exposes the metadata that members
deposit with Crossref when they register their content. And it’s not just the bibliographic metadata either:
funding data, license information, full-text links, ORCID iDs, abstracts, and Crossmark updates are in members’ metadata too.
You can search, facet, filter, or sample metadata from thousands of members, and the results are returned in JSON.

#+INCLUDE: "reviews.org" :lines "35-45"
